#Template
#Animal.create(name: "", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: false, has_stripes: false, has_shell: false, has_tail: false, lives_in_sea: false, lives_on_land: false, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: false, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

#Entries

Animal.create(name: "Alligator", is_tall: false, has_sharp_teeth: true, has_forward_facing_eyes: true, has_spots: false, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: false, lives_in_river: true, can_swim: true, can_fly: false, is_predator: true, is_scavenger: false, eats_meat: true, is_common_pet: false, is_insect: false, is_mammal: false, is_reptile: true, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Ant", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: false, has_stripes: false, has_shell: false, has_tail: false, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: true, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Bear", is_tall: false, has_sharp_teeth: true, has_forward_facing_eyes: true, has_spots: false, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: true, is_scavenger: false, eats_meat: true, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: nil, can_be_poisonous: false)

Animal.create(name: "Bee", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: false, has_stripes: true, has_shell: false, has_tail: false, lives_in_sea: false, lives_on_land: false, lives_in_river: false, can_swim: false, can_fly: true, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: true, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Bird (Tropical)", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: nil, has_stripes: nil, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: nil, can_fly: true, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: true, is_insect: false, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: true, can_be_poisonous: false)

Animal.create(name: "Camel", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: false, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Camel", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: false, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Cat", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: nil, has_stripes: nil, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: nil, can_fly: false, is_predator: nil, is_scavenger: nil, eats_meat: true, is_common_pet: true, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Cheetah", is_tall: false, has_sharp_teeth: true, has_forward_facing_eyes: true, has_spots: true, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: nil, can_fly: false, is_predator: true, is_scavenger: false, eats_meat: true, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: nil, can_be_poisonous: false)

Animal.create(name: "Chicken", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: false, has_stripes: false, has_shell: false, has_tail: nil, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: true, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Cow", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: nil, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: true, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Deer", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: nil, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: nil, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: nil, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Dog", is_tall: false, has_sharp_teeth: true, has_forward_facing_eyes: true, has_spots: nil, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: nil, can_fly: false, is_predator: nil, is_scavenger: nil, eats_meat: true, is_common_pet: true, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: nil, nocturnal: false, used_for_entertainment: nil, can_be_poisonous: false)

Animal.create(name: "Dolphin", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: nil, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: true, lives_on_land: false, lives_in_river: false, can_swim: true, can_fly: false, is_predator: nil, is_scavenger: nil, eats_meat: true, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: true, can_be_poisonous: false)

Animal.create(name: "Duck", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: false, has_spots: nil, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: true, can_fly: false, is_predator: false, is_scavenger: true, eats_meat: false, is_common_pet: false, is_insect: false, is_mammal: true, is_reptile: false, raised_for_food: true, nocturnal: false, used_for_entertainment: false, can_be_poisonous: false)

Animal.create(name: "Eagle", is_tall: false, has_sharp_teeth: false, has_forward_facing_eyes: true, has_spots: false, has_stripes: false, has_shell: false, has_tail: true, lives_in_sea: false, lives_on_land: true, lives_in_river: false, can_swim: false, can_fly: true, is_predator: true, is_scavenger: nil, eats_meat: true, is_common_pet: false, is_insect: false, is_mammal: false, is_reptile: false, raised_for_food: false, nocturnal: false, used_for_entertainment: nil, can_be_poisonous: false)


Analyzer.inject_relations
